Nunit home work
Rimanas/AQA_MTS pull request #6
Opened 2024-02-06 22:22 UTC by Rimanas

2024-02-12 20:40 UTC, wildpioneer requested changes

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/Calculator.cs
> +    public static int DivInt(int a, int b)
Методы должны называться одинаково - повторить перегрузку

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/Calculator.cs
> +        try
Никаких проверок в самом методе быть не должно - все эти случаи надо проверить в тестах

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/Calculator.cs
> +    public static double DivDouble(double a, double b)
Форматирование - пустые строки между методами

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/Calculator.cs
> +        try
Тоже никаких обработок в методе не надо делать

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/UnitTest1.cs
> +            Assert.Throws<Exception>(() => Calculator.DivDouble(5.0d, 0.0d));
Проверить на Double.NaN и Double.Infinity

2024-02-12 20:40 UTC, wildpioneer commented on NUnitHomeWork/UnitTest1.cs
> +    }
Не хватает тестов на Repeat. Retry.

2024-02-13 21:53 UTC, Rimanas commented on NUnitHomeWork/Calculator.cs
> +    public static int DivInt(int a, int b)
fixed

2024-02-13 21:53 UTC, Rimanas commented on NUnitHomeWork/Calculator.cs
> +        try
fixed

2024-02-13 21:54 UTC, Rimanas commented on NUnitHomeWork/Calculator.cs
> +    public static double DivDouble(double a, double b)
fixed

2024-02-13 21:54 UTC, Rimanas commented on NUnitHomeWork/Calculator.cs
> +        try
fixed

2024-02-13 21:54 UTC, Rimanas commented on NUnitHomeWork/UnitTest1.cs
> +            Assert.Throws<Exception>(() => Calculator.DivDouble(5.0d, 0.0d));
fixed

2024-02-13 21:54 UTC, Rimanas commented on NUnitHomeWork/UnitTest1.cs
> +    }
fixed

2024-03-05 06:09 UTC, wildpioneer commented
Проверено

2024-03-05 06:09 UTC, closed without merging